### ISSUE TITLE
File not open for writing

### ISSUE THREAD

**Issue by vjeux** [RuurdBijlsma/tm-item-exchange#2]
I've tried using the plugin but whenever I'm clicking somewhere on the map after choosing an item, there's an exception raised on src/Utils/IXEditor.as (line 350, column 9) that says "File not open for writing!".

I'm very confused since looking at the source, the line before is literally opening the file with write access... https://github.com/RuurdBijlsma/tm-item-exchange/blob/2885453e1e5bcda14f2a22250917204d05a2078d/src/Utils/IXEditor.as#L350

Looking at the file on the file system, it looks like it's able to create the folder and files just fine. The item always come up at 1kb with binary data. So it seems to be able to write things into them.

Any idea what may be happening?

**Comment by RuurdBijlsma** [comment]
In my experience that error usually happens when the file it's trying to open doesn't exist. Does this happen every time when you're trying to import an item? Does it happen with every item? 

The 1kb file is probably the empty file created by the tm editor programatically. That's supposed to be replaced with the item downloaded from ix, but that's not working i guess.

Did you change any settings from the default?

**Comment by RuurdBijlsma** [comment]
Fixed this in https://github.com/RuurdBijlsma/tm-item-exchange/commit/5fc86c82bf7f8c83bf6a77b20e1f54e7b3949638

**Comment by vjeux** [comment]
Thanks! I’ll try again and see if it fixes it!

**Comment by vjeux** [comment]
It works now! Thanks so much for fixing it and the plugin, going to save me a lot of trouble reloading the game over and over <3

**Comment by RuurdBijlsma** [comment]
Great!
